#requires -Version 5
# the correct synthase is "#requires -Version 5" with the # before. Change the -Version number by the version required by your script's cmdlets

<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  MS Visual Studio Code
    Generated on:       02/04/2018
    Generated by:       SP@2018
    Organization:       SIK-NET
    --------------------------------------------------------------------------------
    .SYNOPSIS
    Compare Files List
    .DESCRIPTION
    Compare Files 2 lists

    Versionning
    V1.0 - 02/04/2018 - SP@: Creation
#>



## MODULES


## VARIABLES
$Path1 = "G:\_Serie" # G:\_Serie Z:\SeriesTV
$Path2 = "Z:\SeriesTV"

## FUNCTIONS

## SCRIPT
Write-Host -ForegroundColor Green "Get $Path1"
$FilePath1 = get-childItem -File -Recurse $Path1
Write-Host -ForegroundColor Green "Get $Path2"
$FilePath2 = get-childItem -File -Recurse $Path2

Write-Host -ForegroundColor Green "Start Compare Path 1 : $(($FilePath1 | Measure-Object).count) / Path 2 : $(($FilePath2 | Measure-Object).count)" 
$Result = Compare-Object -ReferenceObject $FilePath1 -DifferenceObject $FilePath2

$Result | Out-GridView
Read-Host "Press any key"
#EOF