#requires -Version 5
# the correct synthase is "#requires -Version 5" with the # before. Change the -Version number by the version required by your script's cmdlets

<#
    .NOTES
    --------------------------------------------------------------------------------
    Code generated by:  %Process%
    Generated on:       %Date%
    Generated by:       %Username%
    Organization:       %Organisation%
    --------------------------------------------------------------------------------
    .SYNOPSIS
    %Short Resume%
    .DESCRIPTION
    %Description of the Script%

    Versionning
    V x.x + %Date% + Description of the change

    V1.0 - 01/12/2017 - SP@: Creation
    V1.1 - 11/12/2017 - SP@: Update function Examples
#>

## MODULES
[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8

## VARIABLES
$Path = "E:\DL\Serie"
$StringChangeFrom = "[ Torrent9.red ] "
$StringChangeTo = ""

## FUNCTIONS
Function MultipleRenaming
{
    <#
    .SYNOPSIS
    Short Resume of the function
    .DESCRIPTION
    Description of function
    .PARAMETER StringChangeFrom
    Short Resume of the Variable job
    .PARAMETER StringChangeTo
    Short Resume of the Variable job
    .PARAMETER Location
    Short Resume of the Variable job
    .EXAMPLE
    Example -VariableExample1 "Test"
    Example "Test"

    Give an example(s) of how to use the function.
    Put the comment under the command

    #>
    [Cmdletbinding()]
    Param (
        [Parameter(Mandatory = $True,Position = 0)][String]$StringChangeFrom,
        [Parameter(Mandatory = $false,Position = 1)][String]$StringChangeTo,
        [Parameter(Mandatory = $false,Position = 2)][String]$Location
    )
    Process
    {
        $FilesToRename = Get-ChildItem -Path $Location -File | Where-Object {$_.Name -match $StringChangeFrom}
        foreach ($File in $FilesToRename)
        {
            $NewFullName = $($($File.DirectoryName)+"\"+$(($File.Name).Replace("$StringChangeFrom","$StringChangeTo")))
            Rename-Item -LiteralPath $($File.Fullname) -NewName $NewFullName
        }
        #Get-ChildItem *.txt | Rename-Item -NewName { $_.name -Replace '\.txt$','.log' }
    }
}


## SCRIPT
MultipleRenaming -StringChangeFrom $StringChangeFrom -StringChangeTo $StringChangeTo -Location $Path



#EOF